# Teste de limite por IP
$ for i in {1..5}; do curl -i http://localhost:8080/; done


# Teste de limite por Token
$ for i in {1..5}; do curl -i -H "API_KEY: teste_123" http://localhost:8080/; done


# Testes com Apache Bench (necessário instalção do Apache bench) :
$ ab -n 10 -c 1 http://localhost:8080/
